export { getTradeStatusCopy } from './tradeStatus'
export { getHomeActiveTradeCopy } from './homeActive'
export {
  getMatchingCopy,
  getMatchedDockCopy,
  getMatchingHeroCopy,
  getMatchingUiMode,
  getMatchingStatusBadgeLabel,
  MATCHING_LEAVE_OK_HINT,
  MATCHING_EXACT_PRIORITY_HINT,
  MATCHING_PROPOSAL_START_NOTICE,
  MATCHING_PROPOSAL_START_NOTICE_LINE1,
  MATCHING_PROPOSAL_START_NOTICE_LINE2,
  MATCHING_PROPOSAL_SKIP_LABEL,
  MATCHING_EMPTY_SEARCHING_TITLE,
  MATCHING_EMPTY_SEARCHING_DESCRIPTION,
  MATCHING_EMPTY_EXACT_TAB,
  MATCHING_EMPTY_NEAR_TAB,
  MATCHING_NEW_CANDIDATE_BANNER,
  MATCHING_FIRST_EXACT_BANNER,
  MATCHING_FIRST_EXACT_CTA,
  MATCHING_APPLY_STALE_CANDIDATE,
  formatMatchingElapsed,
  formatMatchingCountdown,
  getMatchingProposalMatchBadge,
  getMatchingProposalTitle,
  getMatchingProposalSellerDetail,
  getMatchingProposalCtaLabel,
  getMatchingResultHeroCopy,
  getMatchingLiveAnnounce,
} from './matching'
export type { MatchingHeroCopy, MatchingUiMode } from './matching'
export {
  getPaymentHeroTitle,
  getPaymentHeroDescription,
  getPaymentFooterDismissHint,
  getPaymentFooterReportHint,
  getPaymentReportedBuyerBadge,
  getPaymentReportedBuyerTitle,
  getPaymentReportedBuyerDescription,
  getPaymentReportedBuyerOutcome,
  getPaymentReportedBuyerAssetProtection,
  getPaymentReportedBuyerNextSteps,
  getPaymentReportedBuyerCancelHint,
  getPaymentReportedBuyerStatusLine,
  getPaymentReportedBuyerReassuranceLines,
  getPaymentReportedBuyerDelayHint,
  getPaymentCountdownCopy,
} from './payment'
