export const API_ERROR_CODES = {
  BANKS_FETCH_FAILED: 'BANKS_FETCH_FAILED',
  HTTP_ERROR: 'HTTP_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
  LOGIN_ID_ALREADY_EXISTS: 'LOGIN_ID_ALREADY_EXISTS',
  INVALID_LOGIN_ID: 'INVALID_LOGIN_ID',
  INVALID_NICKNAME: 'INVALID_NICKNAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_PIN: 'INVALID_PIN',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_RRN: 'INVALID_RRN',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  RESIDENT_NUMBER_ALREADY_EXISTS: 'RESIDENT_NUMBER_ALREADY_EXISTS',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  OCTOMO_INVALID: 'OCTOMO_INVALID',
  OCTOMO_EXPIRED: 'OCTOMO_EXPIRED',
  ACCOUNT_VERIFY_FAILED: 'ACCOUNT_VERIFY_FAILED',
  ACCOUNT_VERIFY_EXPIRED: 'ACCOUNT_VERIFY_EXPIRED',
  NAME_MISMATCH: 'NAME_MISMATCH',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PASSKEY_FAILED: 'PASSKEY_FAILED',
  SENSITIVE_LOCKED: 'SENSITIVE_LOCKED',
  USER_PENDING: 'USER_PENDING',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_WITHDRAWN: 'ACCOUNT_WITHDRAWN',
  ACTION_REQUIRED: 'ACTION_REQUIRED',
  WAIT_FOR_APPROVAL: 'WAIT_FOR_APPROVAL',
  RECOVERY_FAILED: 'RECOVERY_FAILED',
  SELL_ORDER_UNAVAILABLE: 'SELL_ORDER_UNAVAILABLE',
  CANDIDATE_CHANGED: 'CANDIDATE_CHANGED',
  SELL_ORDER_PENDING_REQUEST: 'SELL_ORDER_PENDING_REQUEST',
  BUY_ORDER_PENDING_REQUEST: 'BUY_ORDER_PENDING_REQUEST',
  MATCHING_BUY_ORDER_NOT_MATCHABLE: 'MATCHING_BUY_ORDER_NOT_MATCHABLE',
  BUY_ORDER_REQUEST_PENDING: 'BUY_ORDER_REQUEST_PENDING',
} as const

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]

const KNOWN_ERROR_CODES = new Set<string>(Object.values(API_ERROR_CODES))
const LEGACY_ERROR_ALIAS: Record<string, ApiErrorCode> = {
  LOGIN_ID_TAKEN: API_ERROR_CODES.LOGIN_ID_ALREADY_EXISTS,
  NICKNAME_TAKEN: API_ERROR_CODES.NICKNAME_ALREADY_EXISTS,
  PHONE_EXISTS: API_ERROR_CODES.PHONE_ALREADY_EXISTS,
  IDENTITY_EXISTS: API_ERROR_CODES.RESIDENT_NUMBER_ALREADY_EXISTS,
  INVALID_CREDENTIALS: API_ERROR_CODES.AUTH_INVALID_CREDENTIALS,
}

export function toApiErrorCode(raw: string | undefined): ApiErrorCode {
  if (raw && KNOWN_ERROR_CODES.has(raw)) {
    return raw as ApiErrorCode
  }
  if (raw && LEGACY_ERROR_ALIAS[raw]) {
    return LEGACY_ERROR_ALIAS[raw]
  }
  return API_ERROR_CODES.HTTP_ERROR
}

export class ApiError extends Error {
  readonly code: ApiErrorCode
  readonly status?: number
  readonly details?: string[]

  constructor(
    code: ApiErrorCode,
    message?: string,
    status?: number,
    details?: string[],
  ) {
    super(message ?? code)
    this.name = 'ApiError'
    this.code = code
    this.status = status
    this.details = details
  }
}
